### ISSUE TITLE
Throws Uncaught TypeError: undefined is not a function on CKEditor load

### ISSUE THREAD

**Issue by afriapps** [aendra-rininsland/ckeditor-letterspacing#1]
Im getting this after following the readme file to install the plugin:

Uncaught TypeError: undefined is not a function - ckeditor.js:24

Not sure what is causing this, Im using V4.4

**Comment by aendra-rininsland** [comment]
Hmm... Will investigate later today.

**Comment by afriapps** [comment]
I did manage to fix this, Ill look and let you know what it was

kind regards
Herman Stander Programming bush man
herman@afriapps.co.za / 072 421 7253 / afriapps.co.za

**Comment by aendra-rininsland** [comment]
@afriapps — Great, thanks! Much appreciated!

**Comment by aendra-rininsland** [comment]
Fixed in 0.1.1.
