### ISSUE TITLE
ACF removes span tags when dynamically populating CKEditor

### ISSUE THREAD

**Issue by rami-dabain** [aendra-rininsland/ckeditor-letterspacing#2]
The letter spacing generated by this plugin, can't be parsed back when dynamically loading content into ckeditor ... in other words, when you load content into ckeditor the spacing that has been created is gone!

**Comment by aendra-rininsland** [comment]
Hi! Will look into that later today.

**Comment by rami-dabain** [comment]
Thanks, will be waiting

**Comment by aendra-rininsland** [comment]
Hi @rami-dabain — I tried using it as per my current implementation and it parsed back properly.

When you say "dynamically loading content into CKEditor", how exactly do you mean?

Thanks!

**Comment by rami-dabain** [comment]
i lead the ckeditor this way : 
`$('#'+content_id).ckeditor();`
and load data into it this way:
`$('#'+content_id).val(data);`

then call the function to display it

**Comment by aendra-rininsland** [comment]
Hi again,
It seems to be a general CKEditor issue. Try just inserting any HTML with a <span> tag into that:

```
$('#editor1').val('<span style="text-decoration: underline;">hurrrrrrrrrrr</span>');
$('#editor1').val();
> "<p>hurrrrrrrrrrr</p>"
```

A workaround is to add "span" to ACF, or disable it altogether:
http://ckeditor.com/ckeditor_4.3_beta/samples/datafiltering.html

**Comment by rami-dabain** [comment]
Thanks, this worked.
Maybe there's a way to let the plugin set it by default? this would be
useful

Kind regards ,
Rami Dabain

On Fri, May 30, 2014 at 3:23 PM, Ændrew Rininsland <notifications@github.com

**Comment by aendra-rininsland** [comment]
@rami-dabain Good point. I've added a line that exempts `span` from ACF and pushed it for version 0.1.2, should work out-of-the-box now! 

I've renamed this issue to better reflect what was happening and changed its status to a bug. Thanks for report!

**Comment by rami-dabain** [comment]
great thank you :)
